// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package graph

type Account struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}
