// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package graph

type Account struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Orders []Order `json:"orders"`
}
type AccountInput struct {
	Name string `json:"name"`
}
type OrderInput struct {
	AccountId string              `json:"accountId"`
	Products  []OrderProductInput `json:"products"`
}
type OrderProductInput struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
}
type OrderedProduct struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
}
type PaginationInput struct {
	Skip *int `json:"skip"`
	Take *int `json:"take"`
}
type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}
type ProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}
