// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package graph

import (
	time "time"
)

type Account struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
type Order struct {
	ID         string    `json:"id"`
	CreatedAt  time.Time `json:"createdAt"`
	TotalPrice *float64  `json:"totalPrice"`
	AccountID  string
}
type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}
