// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_8552c1506daeeb16, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type PostProductRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostProductRequest) Reset()         { *m = PostProductRequest{} }
func (m *PostProductRequest) String() string { return proto.CompactTextString(m) }
func (*PostProductRequest) ProtoMessage()    {}
func (*PostProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_8552c1506daeeb16, []int{1}
}
func (m *PostProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostProductRequest.Unmarshal(m, b)
}
func (m *PostProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostProductRequest.Marshal(b, m, deterministic)
}
func (dst *PostProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostProductRequest.Merge(dst, src)
}
func (m *PostProductRequest) XXX_Size() int {
	return xxx_messageInfo_PostProductRequest.Size(m)
}
func (m *PostProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostProductRequest proto.InternalMessageInfo

func (m *PostProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostProductRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type PostProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostProductResponse) Reset()         { *m = PostProductResponse{} }
func (m *PostProductResponse) String() string { return proto.CompactTextString(m) }
func (*PostProductResponse) ProtoMessage()    {}
func (*PostProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_8552c1506daeeb16, []int{2}
}
func (m *PostProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostProductResponse.Unmarshal(m, b)
}
func (m *PostProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostProductResponse.Marshal(b, m, deterministic)
}
func (dst *PostProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostProductResponse.Merge(dst, src)
}
func (m *PostProductResponse) XXX_Size() int {
	return xxx_messageInfo_PostProductResponse.Size(m)
}
func (m *PostProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostProductResponse proto.InternalMessageInfo

func (m *PostProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_8552c1506daeeb16, []int{3}
}
func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(dst, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_8552c1506daeeb16, []int{4}
}
func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(dst, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductsRequest struct {
	Skip                 uint64   `protobuf:"varint,1,opt,name=skip" json:"skip,omitempty"`
	Take                 uint64   `protobuf:"varint,2,opt,name=take" json:"take,omitempty"`
	Ids                  []string `protobuf:"bytes,3,rep,name=ids" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_8552c1506daeeb16, []int{5}
}
func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(dst, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

func (m *GetProductsRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetProductsRequest) GetTake() uint64 {
	if m != nil {
		return m.Take
	}
	return 0
}

func (m *GetProductsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductsResponse) Reset()         { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()    {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_8552c1506daeeb16, []int{6}
}
func (m *GetProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResponse.Unmarshal(m, b)
}
func (m *GetProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResponse.Merge(dst, src)
}
func (m *GetProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsResponse.Size(m)
}
func (m *GetProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResponse proto.InternalMessageInfo

func (m *GetProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "pb.Product")
	proto.RegisterType((*PostProductRequest)(nil), "pb.PostProductRequest")
	proto.RegisterType((*PostProductResponse)(nil), "pb.PostProductResponse")
	proto.RegisterType((*GetProductRequest)(nil), "pb.GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "pb.GetProductResponse")
	proto.RegisterType((*GetProductsRequest)(nil), "pb.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "pb.GetProductsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogServiceClient interface {
	PostProduct(ctx context.Context, in *PostProductRequest, opts ...grpc.CallOption) (*PostProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
}

type catalogServiceClient struct {
	cc *grpc.ClientConn
}

func NewCatalogServiceClient(cc *grpc.ClientConn) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) PostProduct(ctx context.Context, in *PostProductRequest, opts ...grpc.CallOption) (*PostProductResponse, error) {
	out := new(PostProductResponse)
	err := c.cc.Invoke(ctx, "/pb.CatalogService/PostProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, "/pb.CatalogService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, "/pb.CatalogService/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
type CatalogServiceServer interface {
	PostProduct(context.Context, *PostProductRequest) (*PostProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
}

func RegisterCatalogServiceServer(s *grpc.Server, srv CatalogServiceServer) {
	s.RegisterService(&_CatalogService_serviceDesc, srv)
}

func _CatalogService_PostProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).PostProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatalogService/PostProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).PostProduct(ctx, req.(*PostProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatalogService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatalogService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostProduct",
			Handler:    _CatalogService_PostProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _CatalogService_GetProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _CatalogService_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_catalog_8552c1506daeeb16) }

var fileDescriptor_catalog_8552c1506daeeb16 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x4e, 0xc2, 0x30,
	0x14, 0xc6, 0xe9, 0x3a, 0x45, 0xce, 0x22, 0xd1, 0x83, 0x62, 0xc3, 0xd5, 0x52, 0x63, 0xe4, 0x8a,
	0x0b, 0xbc, 0xf4, 0x4f, 0x48, 0xbc, 0xf0, 0xce, 0x90, 0xfa, 0x02, 0x8e, 0xad, 0x31, 0x0d, 0x4a,
	0xeb, 0x5a, 0x7c, 0x51, 0x5f, 0xc8, 0xd0, 0x01, 0x96, 0x4d, 0x4d, 0xbc, 0x3b, 0xfb, 0xce, 0x39,
	0xfb, 0x7d, 0xfd, 0x5a, 0x38, 0xcc, 0x33, 0x97, 0xbd, 0xea, 0x97, 0x91, 0x29, 0xb5, 0xd3, 0x18,
	0x99, 0x19, 0x97, 0xd0, 0x9e, 0x96, 0xba, 0x58, 0xe6, 0x0e, 0xbb, 0x10, 0xa9, 0x82, 0x91, 0x94,
	0x0c, 0x3b, 0x22, 0x52, 0x05, 0x22, 0xc4, 0x8b, 0xec, 0x4d, 0xb2, 0xc8, 0x2b, 0xbe, 0xc6, 0x14,
	0x92, 0x42, 0xda, 0xbc, 0x54, 0xc6, 0x29, 0xbd, 0x60, 0xd4, 0xb7, 0x42, 0x09, 0x4f, 0x60, 0xcf,
	0x94, 0x2a, 0x97, 0x2c, 0x4e, 0xc9, 0x90, 0x88, 0xea, 0x83, 0x3f, 0x03, 0x4e, 0xb5, 0x75, 0x6b,
	0x94, 0x90, 0xef, 0x4b, 0x69, 0xdd, 0x96, 0x40, 0x7e, 0x27, 0x44, 0x7f, 0x10, 0x68, 0x48, 0xb8,
	0x81, 0xde, 0x0e, 0xc1, 0x1a, 0xbd, 0xb0, 0x12, 0x2f, 0xa0, 0x6d, 0x2a, 0xc9, 0x53, 0x92, 0x71,
	0x32, 0x32, 0xb3, 0xd1, 0x66, 0x6a, 0xd3, 0xe3, 0xe7, 0x70, 0xfc, 0x20, 0xeb, 0xf6, 0x6a, 0x81,
	0xf0, 0x6b, 0xc0, 0x70, 0xe8, 0x7f, 0x84, 0xc7, 0x70, 0xd9, 0x06, 0x09, 0xd8, 0xb9, 0x32, 0x7e,
	0x33, 0x16, 0xbe, 0x5e, 0x69, 0x2e, 0x9b, 0x57, 0xb9, 0xc7, 0xc2, 0xd7, 0x78, 0x04, 0x54, 0x15,
	0x96, 0xd1, 0x94, 0x0e, 0x3b, 0x62, 0x55, 0xf2, 0x3b, 0xe8, 0xed, 0xfc, 0x6f, 0xed, 0xe6, 0x12,
	0x0e, 0xd6, 0x44, 0xcb, 0x48, 0x4a, 0xeb, 0x76, 0xb6, 0xcd, 0xf1, 0x27, 0x81, 0xee, 0x7d, 0xf5,
	0x1c, 0x9e, 0x64, 0xf9, 0xa1, 0x72, 0x89, 0x13, 0x48, 0x82, 0x08, 0xb1, 0xef, 0x17, 0x1b, 0xb7,
	0x36, 0x38, 0x6b, 0xe8, 0x15, 0x9b, 0xb7, 0xf0, 0x16, 0xe0, 0xdb, 0x14, 0x9e, 0xae, 0x06, 0x1b,
	0xb1, 0x0e, 0xfa, 0x75, 0x79, 0xbb, 0x3e, 0x81, 0x24, 0x38, 0x13, 0xd6, 0x06, 0xed, 0x8e, 0x81,
	0x1f, 0x0e, 0xcf, 0x5b, 0xb3, 0x7d, 0xff, 0xb2, 0xaf, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf8,
	0xdb, 0x2d, 0xf8, 0xea, 0x02, 0x00, 0x00,
}
