// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_6f9a70f04637064a, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type PostProductRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostProductRequest) Reset()         { *m = PostProductRequest{} }
func (m *PostProductRequest) String() string { return proto.CompactTextString(m) }
func (*PostProductRequest) ProtoMessage()    {}
func (*PostProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_6f9a70f04637064a, []int{1}
}
func (m *PostProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostProductRequest.Unmarshal(m, b)
}
func (m *PostProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostProductRequest.Marshal(b, m, deterministic)
}
func (dst *PostProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostProductRequest.Merge(dst, src)
}
func (m *PostProductRequest) XXX_Size() int {
	return xxx_messageInfo_PostProductRequest.Size(m)
}
func (m *PostProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostProductRequest proto.InternalMessageInfo

func (m *PostProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostProductRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type PostProductResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostProductResponse) Reset()         { *m = PostProductResponse{} }
func (m *PostProductResponse) String() string { return proto.CompactTextString(m) }
func (*PostProductResponse) ProtoMessage()    {}
func (*PostProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_6f9a70f04637064a, []int{2}
}
func (m *PostProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostProductResponse.Unmarshal(m, b)
}
func (m *PostProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostProductResponse.Marshal(b, m, deterministic)
}
func (dst *PostProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostProductResponse.Merge(dst, src)
}
func (m *PostProductResponse) XXX_Size() int {
	return xxx_messageInfo_PostProductResponse.Size(m)
}
func (m *PostProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostProductResponse proto.InternalMessageInfo

func (m *PostProductResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_6f9a70f04637064a, []int{3}
}
func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(dst, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProductsRequest struct {
	Skip                 uint64   `protobuf:"varint,1,opt,name=skip" json:"skip,omitempty"`
	Take                 uint64   `protobuf:"varint,2,opt,name=take" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_6f9a70f04637064a, []int{4}
}
func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(dst, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

func (m *GetProductsRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetProductsRequest) GetTake() uint64 {
	if m != nil {
		return m.Take
	}
	return 0
}

type GetProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductsResponse) Reset()         { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()    {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_6f9a70f04637064a, []int{5}
}
func (m *GetProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResponse.Unmarshal(m, b)
}
func (m *GetProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResponse.Merge(dst, src)
}
func (m *GetProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsResponse.Size(m)
}
func (m *GetProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResponse proto.InternalMessageInfo

func (m *GetProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "pb.Product")
	proto.RegisterType((*PostProductRequest)(nil), "pb.PostProductRequest")
	proto.RegisterType((*PostProductResponse)(nil), "pb.PostProductResponse")
	proto.RegisterType((*GetProductRequest)(nil), "pb.GetProductRequest")
	proto.RegisterType((*GetProductsRequest)(nil), "pb.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "pb.GetProductsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatalogClient is the client API for Catalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogClient interface {
	PostProduct(ctx context.Context, in *PostProductRequest, opts ...grpc.CallOption) (*PostProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error)
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
}

type catalogClient struct {
	cc *grpc.ClientConn
}

func NewCatalogClient(cc *grpc.ClientConn) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) PostProduct(ctx context.Context, in *PostProductRequest, opts ...grpc.CallOption) (*PostProductResponse, error) {
	out := new(PostProductResponse)
	err := c.cc.Invoke(ctx, "/pb.Catalog/PostProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/pb.Catalog/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, "/pb.Catalog/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServer is the server API for Catalog service.
type CatalogServer interface {
	PostProduct(context.Context, *PostProductRequest) (*PostProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
}

func RegisterCatalogServer(s *grpc.Server, srv CatalogServer) {
	s.RegisterService(&_Catalog_serviceDesc, srv)
}

func _Catalog_PostProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).PostProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Catalog/PostProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).PostProduct(ctx, req.(*PostProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Catalog/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Catalog/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Catalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostProduct",
			Handler:    _Catalog_PostProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _Catalog_GetProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _Catalog_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_catalog_6f9a70f04637064a) }

var fileDescriptor_catalog_6f9a70f04637064a = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x4e, 0xbc, 0x30,
	0x14, 0xc5, 0x29, 0xf0, 0xff, 0x8f, 0x5e, 0xa2, 0x89, 0x77, 0xfc, 0x20, 0xb3, 0x22, 0x35, 0x46,
	0x56, 0x2c, 0x70, 0x6b, 0x8c, 0x89, 0x0b, 0xb7, 0x93, 0x3e, 0x81, 0x7c, 0x34, 0xa6, 0x19, 0xa5,
	0x95, 0x76, 0x1e, 0xd0, 0x37, 0x33, 0xb4, 0x38, 0xd3, 0x01, 0x75, 0x77, 0x39, 0xbd, 0xcd, 0xef,
	0x9c, 0x43, 0xe1, 0xa4, 0xa9, 0x4c, 0xf5, 0x26, 0x5f, 0x0b, 0xd5, 0x4b, 0x23, 0x31, 0x54, 0x35,
	0xe5, 0xb0, 0x58, 0xf7, 0xb2, 0xdd, 0x36, 0x06, 0x4f, 0x21, 0x14, 0x6d, 0x4a, 0x32, 0x92, 0x1f,
	0xb3, 0x50, 0xb4, 0x88, 0x10, 0x77, 0xd5, 0x3b, 0x4f, 0x43, 0xab, 0xd8, 0x19, 0x33, 0x48, 0x5a,
	0xae, 0x9b, 0x5e, 0x28, 0x23, 0x64, 0x97, 0x46, 0xf6, 0xc8, 0x97, 0xf0, 0x1c, 0xfe, 0xa9, 0x5e,
	0x34, 0x3c, 0x8d, 0x33, 0x92, 0x13, 0xe6, 0x3e, 0xe8, 0x0b, 0xe0, 0x5a, 0x6a, 0x33, 0xa2, 0x18,
	0xff, 0xd8, 0x72, 0x6d, 0x76, 0x04, 0xf2, 0x3b, 0x21, 0xfc, 0x83, 0x10, 0xf9, 0x84, 0x1b, 0x58,
	0x1e, 0x10, 0xb4, 0x92, 0x9d, 0xe6, 0xd3, 0x50, 0xf4, 0x1a, 0xce, 0x9e, 0xf9, 0xd4, 0xc7, 0x74,
	0xe9, 0x1e, 0x70, 0xbf, 0xa4, 0x3d, 0xb7, 0x7a, 0x23, 0x94, 0xdd, 0x8b, 0x99, 0x9d, 0x07, 0xcd,
	0x54, 0x1b, 0xd7, 0x51, 0xcc, 0xec, 0x4c, 0x1f, 0x60, 0x79, 0x70, 0x7b, 0x74, 0x72, 0x0b, 0x47,
	0x6a, 0xd4, 0x52, 0x92, 0x45, 0x79, 0x52, 0x26, 0x85, 0xaa, 0x8b, 0x6f, 0x2b, 0xbb, 0xc3, 0xf2,
	0x93, 0xc0, 0xe2, 0xc9, 0xfd, 0x28, 0x7c, 0x84, 0xc4, 0x4b, 0x85, 0x97, 0xf6, 0xc6, 0xac, 0xc8,
	0xd5, 0xd5, 0x4c, 0x77, 0x50, 0x1a, 0x60, 0x09, 0xb0, 0x77, 0x83, 0x17, 0xc3, 0xe2, 0xac, 0x80,
	0x95, 0xef, 0x84, 0x06, 0x03, 0xd5, 0x4b, 0xe0, 0xa8, 0xf3, 0x42, 0x1c, 0xf5, 0x87, 0xa8, 0x34,
	0xa8, 0xff, 0xdb, 0x17, 0x76, 0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xee, 0x2c, 0x4d, 0x72,
	0x02, 0x00, 0x00,
}
