// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAccountRequest) Reset()         { *m = PostAccountRequest{} }
func (m *PostAccountRequest) String() string { return proto.CompactTextString(m) }
func (*PostAccountRequest) ProtoMessage()    {}
func (*PostAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d781fd116377228e, []int{0}
}
func (m *PostAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAccountRequest.Unmarshal(m, b)
}
func (m *PostAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAccountRequest.Marshal(b, m, deterministic)
}
func (dst *PostAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAccountRequest.Merge(dst, src)
}
func (m *PostAccountRequest) XXX_Size() int {
	return xxx_messageInfo_PostAccountRequest.Size(m)
}
func (m *PostAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostAccountRequest proto.InternalMessageInfo

func (m *PostAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PostAccountResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAccountResponse) Reset()         { *m = PostAccountResponse{} }
func (m *PostAccountResponse) String() string { return proto.CompactTextString(m) }
func (*PostAccountResponse) ProtoMessage()    {}
func (*PostAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d781fd116377228e, []int{1}
}
func (m *PostAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAccountResponse.Unmarshal(m, b)
}
func (m *PostAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAccountResponse.Marshal(b, m, deterministic)
}
func (dst *PostAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAccountResponse.Merge(dst, src)
}
func (m *PostAccountResponse) XXX_Size() int {
	return xxx_messageInfo_PostAccountResponse.Size(m)
}
func (m *PostAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostAccountResponse proto.InternalMessageInfo

func (m *PostAccountResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PostAccountResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d781fd116377228e, []int{2}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAccountResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_d781fd116377228e, []int{3}
}
func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(dst, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetAccountResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PostAccountRequest)(nil), "pb.PostAccountRequest")
	proto.RegisterType((*PostAccountResponse)(nil), "pb.PostAccountResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "pb.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "pb.GetAccountResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	PostAccount(ctx context.Context, in *PostAccountRequest, opts ...grpc.CallOption) (*PostAccountResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) PostAccount(ctx context.Context, in *PostAccountRequest, opts ...grpc.CallOption) (*PostAccountResponse, error) {
	out := new(PostAccountResponse)
	err := c.cc.Invoke(ctx, "/pb.Account/PostAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/pb.Account/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	PostAccount(context.Context, *PostAccountRequest) (*PostAccountResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_PostAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).PostAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Account/PostAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).PostAccount(ctx, req.(*PostAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Account/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostAccount",
			Handler:    _Account_PostAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _Account_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_d781fd116377228e) }

var fileDescriptor_account_d781fd116377228e = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xd2, 0xe0,
	0x12, 0x0a, 0xc8, 0x2f, 0x2e, 0x71, 0x84, 0x48, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x4a, 0x96, 0x5c, 0xc2, 0x28, 0x2a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xf8, 0xb8, 0x98,
	0x32, 0x53, 0xa0, 0x0a, 0x99, 0x32, 0x53, 0xe0, 0x5a, 0x99, 0x90, 0xb4, 0x2a, 0x73, 0x09, 0xba,
	0xa7, 0xa2, 0xdb, 0x81, 0xa6, 0x51, 0xc9, 0x82, 0x4b, 0x08, 0x59, 0x11, 0xf1, 0xc6, 0x1b, 0x75,
	0x31, 0x72, 0xb1, 0x43, 0xf5, 0x09, 0x39, 0x70, 0x71, 0x23, 0xb9, 0x52, 0x48, 0x4c, 0xaf, 0x20,
	0x49, 0x0f, 0xd3, 0x83, 0x52, 0xe2, 0x18, 0xe2, 0x10, 0xfb, 0x94, 0x18, 0x84, 0x6c, 0xb9, 0xb8,
	0x10, 0xee, 0x10, 0x12, 0x05, 0x29, 0xc4, 0x70, 0xbc, 0x94, 0x18, 0xba, 0x30, 0x4c, 0x7b, 0x12,
	0x1b, 0x38, 0x6c, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x34, 0xf9, 0xd5, 0x67, 0x6c, 0x01,
	0x00, 0x00,
}
